import { BatchEncoderConstructorOptions, BatchEncoderDependencies } from './batch-encoder';
import { CipherTextConstructorOptions, CipherTextDependencies } from './cipher-text';
import { CKKSEncoderConstructorOptions, CKKSEncoderDependencies } from './ckks-encoder';
import { CoeffModulus, CoeffModulusDependencies } from './coeff-modulus';
import { ComprModeType, ComprModeTypeDependencies } from './compr-mode-type';
import { ContextDataConstructorOptions, ContextDataDependencies } from './context-data';
import { ContextConstructorOptions, ContextDependencies } from './context';
import { DecryptorConstructorOptions, DecryptorDependencies } from './decryptor';
import { EncryptionParameterQualifiersConstructorOptions, EncryptionParameterQualifiersDependencies } from './encryption-parameter-qualifiers';
import { EncryptionParametersConstructorOptions, EncryptionParametersDependencies } from './encryption-parameters';
import { EncryptorConstructorOptions, EncryptorDependencies } from './encryptor';
import { EvaluatorConstructorOptions, EvaluatorDependencies } from './evaluator';
import { Exception, ExceptionDependencies } from './exception';
import { GaloisKeysConstructorOptions, GaloisKeysDependencies } from './galois-keys';
import { IntegerEncoderConstructorOptions, IntegerEncoderDependencies } from './integer-encoder';
import { MemoryPoolHandle, MemoryPoolHandleDependencies } from './memory-pool-handle';
import { ModulusConstructorOptions, ModulusDependencies } from './modulus';
import { ParmsIdTypeConstructorOptions, ParmsIdTypeDependencies } from './parms-id-type';
import { PlainTextConstructorOptions, PlainTextDependencies } from './plain-text';
import { PlainModulus, PlainModulusDependencies } from './plain-modulus';
import { PublicKeyConstructorOptions, PublicKeyDependencies } from './public-key';
import { RelinKeysConstructorOptions, RelinKeysDependencies } from './relin-keys';
import { SchemeType, SchemeTypeDependencies } from './scheme-type';
import { SecretKeyConstructorOptions, SecretKeyDependencies } from './secret-key';
import { SecurityLevel, SecurityLevelDependencies } from './security-level';
import { SerializableConstructorOptions, SerializableDependencies } from './serializable';
import { VectorConstructorOptions, VectorDependencies } from './vector';
import { KeyGeneratorConstructorOptions, KeyGeneratorDependencies } from './key-generator';
export declare type Instance = any;
export declare type Loader = any;
export declare type Library = any;
export declare type Dependencies = any;
export declare type LoaderOptions = {
    readonly loader: Loader;
};
export declare type SEALLibrary = {
    readonly BatchEncoder: BatchEncoderConstructorOptions;
    readonly CipherText: CipherTextConstructorOptions;
    readonly CKKSEncoder: CKKSEncoderConstructorOptions;
    readonly CoeffModulus: CoeffModulus;
    readonly ComprModeType: ComprModeType;
    readonly ContextData: ContextDataConstructorOptions;
    readonly Context: ContextConstructorOptions;
    readonly Decryptor: DecryptorConstructorOptions;
    readonly EncryptionParameterQualifiers: EncryptionParameterQualifiersConstructorOptions;
    readonly EncryptionParameters: EncryptionParametersConstructorOptions;
    readonly Encryptor: EncryptorConstructorOptions;
    readonly Evaluator: EvaluatorConstructorOptions;
    readonly Exception: Exception;
    readonly GaloisKeys: GaloisKeysConstructorOptions;
    readonly KeyGenerator: KeyGeneratorConstructorOptions;
    readonly IntegerEncoder: IntegerEncoderConstructorOptions;
    readonly MemoryPoolHandle: MemoryPoolHandle;
    readonly Modulus: ModulusConstructorOptions;
    readonly ParmsIdType: ParmsIdTypeConstructorOptions;
    readonly PlainText: PlainTextConstructorOptions;
    readonly PlainModulus: PlainModulus;
    readonly PublicKey: PublicKeyConstructorOptions;
    readonly RelinKeys: RelinKeysConstructorOptions;
    readonly SchemeType: SchemeType;
    readonly SecretKey: SecretKeyConstructorOptions;
    readonly SecurityLevel: SecurityLevel;
    readonly Serializable: SerializableConstructorOptions;
    readonly Vector: VectorConstructorOptions;
};
declare type SEALConstructorOptions = {
    readonly BatchEncoder: BatchEncoderDependencies;
    readonly CipherText: CipherTextDependencies;
    readonly CKKSEncoder: CKKSEncoderDependencies;
    readonly CoeffModulus: CoeffModulusDependencies;
    readonly ComprModeType: ComprModeTypeDependencies;
    readonly ContextData: ContextDataDependencies;
    readonly Context: ContextDependencies;
    readonly Decryptor: DecryptorDependencies;
    readonly EncryptionParameterQualifiers: EncryptionParameterQualifiersDependencies;
    readonly EncryptionParameters: EncryptionParametersDependencies;
    readonly Encryptor: EncryptorDependencies;
    readonly Evaluator: EvaluatorDependencies;
    readonly Exception: ExceptionDependencies;
    readonly GaloisKeys: GaloisKeysDependencies;
    readonly KeyGenerator: KeyGeneratorDependencies;
    readonly IntegerEncoder: IntegerEncoderDependencies;
    readonly MemoryPoolHandle: MemoryPoolHandleDependencies;
    readonly Modulus: ModulusDependencies;
    readonly ParmsIdType: ParmsIdTypeDependencies;
    readonly PlainText: PlainTextDependencies;
    readonly PlainModulus: PlainModulusDependencies;
    readonly PublicKey: PublicKeyDependencies;
    readonly RelinKeys: RelinKeysDependencies;
    readonly SchemeType: SchemeTypeDependencies;
    readonly SecretKey: SecretKeyDependencies;
    readonly SecurityLevel: SecurityLevelDependencies;
    readonly Serializable: SerializableDependencies;
    readonly Vector: VectorDependencies;
};
export declare const SEALConstructor: ({ BatchEncoder, CipherText, CKKSEncoder, CoeffModulus, ComprModeType, ContextData, Context, Decryptor, EncryptionParameterQualifiers, EncryptionParameters, Encryptor, Evaluator, Exception, GaloisKeys, KeyGenerator, IntegerEncoder, MemoryPoolHandle, Modulus, ParmsIdType, PlainText, PlainModulus, PublicKey, RelinKeys, SchemeType, SecretKey, SecurityLevel, Serializable, Vector }: SEALConstructorOptions) => SEALLibrary;
export {};
